#Update all the sections by editing the data.yml file inside _data folder.

# Site Settings
title: Kevin's Resume
url: #

#change it according to your repository name
# disabling since we are using a custom domain
#baseurl: '/online-cv' 

description: This ius my description <style>.embed-container {position: relative; padding-bottom: 80%; height: 0; max-width: 100%;} .embed-container iframe, .embed-container object, .embed-container iframe{position: absolute; top: 0; left: 0; width: 100%; height: 100%;} small{position: absolute; z-index: 40; bottom: 0; margin-bottom: -15px;}</style><div class="embed-container"><iframe width="500" height="400" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" title="test map" src="//csurams.maps.arcgis.com/apps/Embed/index.html?webmap=ebd8f5911cdd4e4a912e92598cd8993a&extent=-180,-82.8315,180,82.8315&zoom=true&previewImage=false&scale=true&disable_scroll=false&theme=light"></iframe></div>
# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: blue # blue turquoise green berry orange ceramic
chrome_mobile_color: #use hex colors (ex:#1976d2) or leave empty if you don't want a color for chrome mobile searchbar

# Tracker
analytics: UA-83979019-1

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: 0.0.0.0
safe: false
